### ISSUE TITLE
LD pruning for PCA

### ISSUE THREAD

**Issue by Homap** [dcgerard/ldsep#6]
Dear David,

Thank you very much for your great R package. I have a question regarding LD pruning. I'd like to use the glpca function in adegenet package to conduct PCA in my samples (20 diploids individuals, 6 tetraploids and 4 hexaploids). I have pruned the SNPs for my diploid samples using plink, however, I am not sure how I could do that for my polyploids since plink does not accept polyploid data as input. When using ldsep and obtaining the matrix of pairwise LD, I was wondering how I could use that to prune my data for LD?

Thank you very much in advance,
Homa

**Comment by dcgerard** [comment]
Hey Homa,

Thanks for your interest in `{ldsep}`!

Right now, I haven't implemented any LD pruning methods, but this is something that I plan on eventually getting to. I'll let you know when I get around to it.

Best,
David

**Comment by Homap** [comment]
Thanks a lot, I am looking forward to it!
